<?php
/**
 * Mailer service — reads all SMTP config from .env (via env()).
 * No credentials are hardcoded here. Requires phpmailer/phpmailer
 * (composer require phpmailer/phpmailer).
 *
 * Place this wherever your project keeps services, e.g. app/Services/Mailer.php
 * Make sure env.php (your .env loader) has already run before this is used.
 */

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception as PHPMailerException;

class Mailer
{
    /**
     * Returns true if MAIL_MAILER is configured with enough info to send.
     * Mirrors the check that produces the "Email sending is not configured
     * on this server yet" error.
     */
    public static function isConfigured(): bool
    {
        $mailer = env('MAIL_MAILER', 'log');

        if ($mailer === 'log') {
            return true; // log mode always "works" — just doesn't deliver
        }

        if ($mailer === 'smtp') {
            return !empty(env('MAIL_HOST'))
                && !empty(env('MAIL_USERNAME'))
                && !empty(env('MAIL_PASSWORD'));
        }

        if ($mailer === 'mail') {
            return true; // relies on server's local MTA, no extra config needed
        }

        return false;
    }

    /**
     * Core send method. Returns [success(bool), errorMessage(string|null)].
     */
    public static function send(string $toEmail, string $toName, string $subject, string $htmlBody, string $plainBody = ''): array
    {
        $mailerDriver = env('MAIL_MAILER', 'log');

        // --- log driver: write to storage/logs/mail.log, don't actually send ---
        if ($mailerDriver === 'log') {
            $logPath = dirname(__DIR__) . '/storage/logs/mail.log';
            $entry = sprintf(
                "[%s] To: %s <%s> | Subject: %s\n%s\n%s\n\n",
                date('Y-m-d H:i:s'),
                $toName,
                $toEmail,
                $subject,
                $plainBody ?: strip_tags($htmlBody),
                str_repeat('-', 60)
            );
            @file_put_contents($logPath, $entry, FILE_APPEND);
            return [true, null];
        }

        if (!self::isConfigured()) {
            return [false, 'Email sending is not configured on this server yet. Please contact your administrator, or see Settings > Mail Setup.'];
        }

        $mail = new PHPMailer(true);

        try {
            if ($mailerDriver === 'smtp') {
                $mail->isSMTP();
                $mail->Host       = env('MAIL_HOST');
                $mail->SMTPAuth   = true;
                $mail->Username   = env('MAIL_USERNAME');
                $mail->Password   = env('MAIL_PASSWORD');
                $mail->SMTPSecure = env('MAIL_ENCRYPTION', 'tls'); // 'tls' or 'ssl'
                $mail->Port       = (int) env('MAIL_PORT', 587);
            } else {
                $mail->isMail(); // PHP's native mail(), needs local MTA
            }

            $mail->setFrom(env('MAIL_FROM_ADDRESS'), env('MAIL_FROM_NAME', env('APP_NAME', 'App')));
            $mail->addAddress($toEmail, $toName);

            $mail->isHTML(true);
            $mail->Subject = $subject;
            $mail->Body    = $htmlBody;
            $mail->AltBody = $plainBody ?: strip_tags($htmlBody);

            $mail->send();
            return [true, null];
        } catch (PHPMailerException $e) {
            error_log('Mailer error: ' . $mail->ErrorInfo);
            return [false, 'Failed to send email. Please try again later or contact your administrator.'];
        }
    }

    /**
     * Password reset — sends the OTP code generated by your reset-password flow.
     * $otp and $ttlMinutes should come from your existing OTP generation logic
     * (OTP_LENGTH / OTP_TTL_MINUTES from .env).
     */
    public static function sendPasswordResetOtp(string $toEmail, string $toName, string $otp, int $ttlMinutes): array
    {
        $appName = env('APP_NAME', 'App');
        $subject = "{$appName} — Password Reset Code";

        $htmlBody = <<<HTML
            <div style="font-family: Arial, sans-serif; max-width: 480px; margin: auto;">
                <h2 style="color:#333;">Password Reset Request</h2>
                <p>Hi {$toName},</p>
                <p>Use the code below to reset your password. This code expires in {$ttlMinutes} minutes.</p>
                <p style="font-size: 28px; font-weight: bold; letter-spacing: 4px; text-align: center; background:#f4f4f4; padding: 12px; border-radius: 6px;">{$otp}</p>
                <p>If you did not request a password reset, you can safely ignore this email.</p>
                <p style="color:#888; font-size: 12px;">{$appName}</p>
            </div>
        HTML;

        $plainBody = "Your password reset code is: {$otp}\nThis code expires in {$ttlMinutes} minutes.\nIf you did not request this, ignore this email.";

        return self::send($toEmail, $toName, $subject, $htmlBody, $plainBody);
    }

    /**
     * Login OTP / verification — e.g. for a login-time 2FA code or
     * email-verification-on-login flow.
     */
    public static function sendLoginOtp(string $toEmail, string $toName, string $otp, int $ttlMinutes): array
    {
        $appName = env('APP_NAME', 'App');
        $subject = "{$appName} — Login Verification Code";

        $htmlBody = <<<HTML
            <div style="font-family: Arial, sans-serif; max-width: 480px; margin: auto;">
                <h2 style="color:#333;">Login Verification</h2>
                <p>Hi {$toName},</p>
                <p>Use the code below to complete your login. This code expires in {$ttlMinutes} minutes.</p>
                <p style="font-size: 28px; font-weight: bold; letter-spacing: 4px; text-align: center; background:#f4f4f4; padding: 12px; border-radius: 6px;">{$otp}</p>
                <p>If this wasn't you, please secure your account immediately.</p>
                <p style="color:#888; font-size: 12px;">{$appName}</p>
            </div>
        HTML;

        $plainBody = "Your login verification code is: {$otp}\nThis code expires in {$ttlMinutes} minutes.\nIf this wasn't you, secure your account immediately.";

        return self::send($toEmail, $toName, $subject, $htmlBody, $plainBody);
    }
}
